version: "3.8"

services:
  backend_dev:
    container_name: backend_dev
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    tty: true
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/backend
    depends_on:
      - db_dev
    env_file:
      - .env

  db_dev:
    image: postgres:16.2
    container_name: db_dev
    restart: always
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data 


  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    restart: always
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_PASSWORD}
    env_file:
      - .env
    ports:
      - "5050:80"
    depends_on:
      - db_dev
    volumes:
      - pgadmin-data:/var/lib/pgadmin


volumes:
  pgdata:
  pgadmin-data:

