version: "3.8"

services:
  backend_test:
    container_name: backend_test
    build:
      context: ./backend
      dockerfile: Dockerfile.test
    tty: true
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/backend
    depends_on:
      - db_test
    env_file:
      - .env.example

  db_test:
    image: postgres:16.2
    container_name: db_test
    restart: always
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    env_file:
      - .env
    ports:
      - "5433:5433"
    volumes:
      - pgdata:/var/lib/postgresql/data 

volumes:
  pgdata:
